- name: install repis release
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true
    
- name: enabling remis release
  ansible.builtin.command: dnf module enable redis:remi-6.2 -y

- name: Installing redis
  ansible.builtin.package:
    name: redis
    state: present

- name: Giving remote access
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes     