- name: Copying MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Starting and Enabling the MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started 
    enabled: yes   

- name: Replace old hostname with new hostname (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted       