- name: disabling MySQL 8 version
  ansible.builtin.command: dnf module disable mysql -y

- name: Copying the MySQL5.7 repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing MySQL Server
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Starting and enabling MySQL Service
  ansible.builtin.service:
    name: mysqld
    state: restarted   
    enabled: yes

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1 