- name: Installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Removing the default content that web server is serving.  
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating new html directory  
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory   

- name: Downloading the frontend content
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: extarcting the frontend content
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html  
    remote_src: yes

- name: Copying roboshop.conf file
  ansible.builtin.template:
    src: roboshop.conf.j2
    dest: /etc/nginx/default.d/roboshop.conf
  notify:
  - Restart nginx  

