- name: install go
  ansible.install.dnf:
  name: golang

- name: build go application
  ansible.builtin.command: "{{item}}"
  loop:
  - go mod init dispatch
  - go get 
  - go build
  args:
    chdir: /app
  