- name: disable old nodejs and enable nodejs:18
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Installing nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Installing Dependencies
  ansible.builtin.command: npm install 
  args:
    chdir: /app