- name: "Copying {{component}}.service in systemd"
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/catalogue.service

- name: Loading the service.
  ansible.builtin.systemd_service:    
    daemon_reload: true

- name: starting and enabling the service
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes     