- name: App-Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Setting up Nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs    

- name: setting catalogue service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd        